Improvements

diff --git a/Jenkinsfile-k8s b/Jenkinsfile-k8s
--- a/Jenkinsfile-k8s
+++ b/Jenkinsfile-k8s
@@ -1,46 +1,55 @@
 pipeline {
-   agent any
+  agent any
 
-   environment {
-      APP_NAME = "complete-production-e2e-pipeline"
-      OCI_SERVER = "zrh.ocir.io"
-      OCI_NAMESPACE = "zrexacpiqwde"
-      OCI_REPO = "trader_go"
-      OCI_IMAGE_NAME = "${OCI_SERVER}/${OCI_NAMESPACE}/${APP_NAME}:latest"
-   }
+  environment {
+    APP_NAME = "complete-production-e2e-pipeline"
+    OCI_SERVER = "zrh.ocir.io"
+    OCI_NAMESPACE = "zrexacpiqwde"
+    OCI_REPO = "trader_go"
+    OCI_IMAGE_NAME = "${OCI_SERVER}/${OCI_NAMESPACE}/${APP_NAME}:latest"
+  }
 
-   stages {
-      stage("Cleanup Workspace") {
-         steps {
-            cleanWs()
-         }
+  stages {
+    stage("Cleanup Workspace") {
+      steps {
+        cleanWs()
       }
+    }
 
-      stage("Checkout from SCM") {
-         steps {
-            git branch: 'main', credentialsId: 'github-credentials', url: 'https://github.com/siqueiraa/complete-prodcution-e2e-pipeline.git'
-         }
+    stage("Checkout from SCM") {
+      steps {
+        git branch: 'main', credentialsId: 'github-credentials', url: 'https://github.com/siqueiraa/complete-prodcution-e2e-pipeline.git'
       }
+    }
 
-      stage("Verify OCI CLI and Kubernetes Connection") {
-         steps {
-            withCredentials([oci(credentialsId: 'ociconfig')]) {
-               sh '''
-                  echo "Checking Kubernetes connection..."
-                  kubectl get pods -n jenkins
-               '''
-            }
-         }
+    stage("Verify OCI CLI and Kubernetes Connection") {
+      steps {
+        withCredentials([oci(credentialsId: 'ociconfig')]) {
+          withKubeConfig([credentialsId: 'k8s']) {
+            sh '''
+              echo "Checking OCI CLI installation..."
+              if ! command -v oci &> /dev/null
+              then
+                  echo "OCI CLI could not be found"
+                  exit 1
+              fi
+              echo "OCI CLI found: $(oci --version)"
+              echo "Checking Kubernetes connection..."
+              kubectl get pods -n jenkins
+            '''
+          }
+        }
       }
+    }
 
-      stage("Build & Push with Kaniko") {
-         steps {
-            container('kaniko') {
-               sh '''#!/busybox/sh
-                   /kaniko/executor --dockerfile="${WORKSPACE}/Dockerfile" --context="${WORKSPACE}" --destination="${OCI_IMAGE_NAME}"
-               '''
-            }
-         }
+    stage("Build & Push with Kaniko") {
+      steps {
+        container('kaniko') {
+          sh '''#!/busybox/sh
+              /kaniko/executor --dockerfile="${WORKSPACE}/Dockerfile" --context="${WORKSPACE}" --destination="${OCI_IMAGE_NAME}"
+            '''
+        }
       }
-   }
+    }
+  }
 }
